# Generated by Django 4.2.3 on 2023-11-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
