# Generated by Django 4.2.3 on 2023-11-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcafe', '0002_venta_fecha_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fecha_venta',
            new_name='fecha_compra',
        ),
    ]
